spring:
  datasource:
    url: jdbc:h2:file:./data/sample
    username: sa
    password:
    driverClassName: org.h2.Driver
#    url: jdbc:postgresql://localhost:5432/task_tracker
#    username: postgres
#    password: postgres
#    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  profiles:
#    active: dev
#csv:
#  user:
#    stringpath: "homework-2/src/main/resources/Users.csv"
#  task:
#    stringpath: "homework-2/src/main/resources/Tasks.csv"
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG